DEFAULT_HSV_MIN_HUE = 3
DEFAULT_HSV_MAX_HUE = 3
DEFAULT_HSV_MIN_VALUE = 100
DEFAULT_HSV_MAX_VALUE = 120
DEFAULT_HSV_MIN_SATURATION = 100
DEFAULT_HSV_MAX_SATURATION = 120
DASHBOARD_HEIGHT = 140
DEFAULT_CAM_FPS = 30
